In [1]:
import pandas as pd

In [33]:
data=pd.read_csv("5.csv")
data

,Company,url,Content,History,Operations,Business,Products and services,Awards and recognition,new_History,Images,Image_Description,History_Tel,Operations_Tel,Business_Tel,Products and services_Tel,Awards and recognition_Tel,Awards,Awards_Tel
0,Adani Enterprises Ltd.,https://en.wikipedia.org/wiki/Adani_Enterprises,Adani Enterprises Limited\nGrowth with Goodnes...,The holding company was incorporated in 1993 u...,NaN,NaN,NaN,NaN,Adani Enterprises LimitedGrowth with GoodnessT...,['https://upload.wikimedia.org/wikipedia/commo...,['Growth with Goodness'],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adani Green Energy Ltd.,https://en.wikipedia.org/wiki/Adani_Green_Energy,Adani Green Energy Limited\nAerial view of Kam...,"The company was incorporated on January 23, 20...","Currently, the company manages 5,290 MW of win...",NaN,NaN,NaN,Adani Green Energy LimitedAerial view of Kamut...,['https://upload.wikimedia.org/wikipedia/commo...,['Aerial view of Kamuthi Solar Power Project'],"కంపెనీ జనవరి 23, 2015న కంపెనీల చట్టం 2013 కింద...",NaN,NaN,NaN,NaN,NaN,NaN
2,Adani Ports and Special Economic Zone Ltd.,https://en.wikipedia.org/wiki/Adani_Ports_%26_SEZ,Adani Ports and Special Economic Zone Limited\...,NaN,NaN,NaN,NaN,"In 2019, the organisation won an 'Honorary Spe...",Adani Ports and Special Economic Zone LimitedT...,['https://upload.wikimedia.org/wikipedia/en/th...,[],NaN,NaN,NaN,NaN,"2019లో, సంస్థ మొట్టమొదటి జాతీయ CSR అవార్డు వేడ...",NaN,NaN
3,Adani Transmission Ltd.,https://en.wikipedia.org/wiki/Adani_Transmission,Adani Transmission Limited\nType Public\nTrade...,Adani Transmission was founded by Gautam Adani...,NaN,NaN,NaN,NaN,Adani Transmission LimitedType PublicTraded as...,NaN,NaN,అదానీ ఎంటర్ప్రైజెస్ నుండి దశాబ్దాల నాటి ట్రాన్...,NaN,NaN,NaN,NaN,NaN,NaN
4,Asian Paints Ltd.,https://en.wikipedia.org/wiki/Asian_Paints,Asian Paints Ltd.\nType Public\nTraded as\nBSE...,The company was started in a garage in Gaiwadi...,NaN,NaN,NaN,NaN,Asian Paints Ltd.Type PublicTraded asBSE: 5008...,NaN,NaN,ఈ కంపెనీని నలుగురు స్నేహితులు చంపక్లాల్ చోక్సీ...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Vivimed Labs Ltd.,https://en.wikipedia.org/wiki/Vivimed_Labs,Vivimed Labs Limited\nType Public Limited Comp...,Vivimed was originally incorporated as M/s Emg...,NaN,NaN,NaN,NaN,Vivimed Labs LimitedType Public Limited Compan...,NaN,NaN,Vivimed నిజానికి 1988లో M/s Emgi ఫార్మాస్యూటిక...,NaN,NaN,NaN,NaN,NaN,NaN
497,VTM Ltd.,https://en.wikipedia.org/wiki/VTM,VTM may refer to:\nNevatim Airbase (IATA code:...,NaN,NaN,NaN,NaN,NaN,VTM may refer to:Nevatim Airbase (IATA code: V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,Walchandnagar Industries Ltd.,https://en.wikipedia.org/wiki/Walchandnagar_In...,Walchandnagar Industries Limited\nType Public ...,Walchandnagar Industries was founded by Walcha...,NaN,NaN,NaN,NaN,Walchandnagar Industries LimitedType Public co...,NaN,NaN,వాల్చంద్నగర్ ఇండస్ట్రీస్ను వాల్చంద్ హీరాచంద్ ద...,NaN,NaN,NaN,NaN,NaN,NaN
499,Weizmann Ltd.,https://en.wikipedia.org/wiki/Weizmann,"Weizman(n) is a surname, common among the Jews...",NaN,NaN,NaN,NaN,NaN,"Weizman(n) is a surname, common among the Jews...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,Zee Learn Ltd.,https://en.wikipedia.org/wiki/Zee_Learn,Zee Learn Limited\nCountry India\nHeadquarters...,NaN,NaN,NaN,NaN,NaN,Zee Learn LimitedCountry IndiaHeadquarters Mum...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
len(data)

501

In [9]:
data2=pd.read_csv("translated_bse_nse.csv")

In [ ]:
data2

In [13]:
data3=data2[data2['url'].notna()]

In [39]:
data3['Awards']=data['Awards_Tel']

C:\Users\LAVAYANA\AppData\Local\Temp\ipykernel_6052\1512090971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3['Awards']=data['Awards_Tel']

In [40]:
data3.to_csv("fullwikicmp.csv",index=False)

In [22]:
data3.shape

(501, 48)

In [26]:
df=pd.merge(data3,data,on='url',how='inner')

In [27]:
df

,Company_x,BSE code,NSE code,ISIN,Sector,Industry,Date,Price,1 day change(%),52 Week Low,...,new_History,Images,Image_Description,History_Tel,Operations_Tel,Business_Tel,Products and services_Tel,Awards and recognition_Tel,Awards,Awards_Tel
0,అదానీ ఎంటర్‌ప్రైజెస్ లిమిటెడ్,512599,అడానియంట్,INE423A01024,సేవలు,ట్రేడింగ్,08-04-2022,"2,170.95",3.43,"1,051.05",...,Adani Enterprises LimitedGrowth with GoodnessT...,['https://upload.wikimedia.org/wikipedia/commo...,['Growth with Goodness'],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,అదానీ గ్రీన్ ఎనర్జీ లిమిటెడ్,541450,అడానిగ్రీన్,INE364U01010,మూలధన వస్తువులు,పవర్ ప్రాజెక్ట్స్,08-04-2022,"2,321.85",7.20,874.8,...,Adani Green Energy LimitedAerial view of Kamut...,['https://upload.wikimedia.org/wikipedia/commo...,['Aerial view of Kamuthi Solar Power Project'],"కంపెనీ జనవరి 23, 2015న కంపెనీల చట్టం 2013 కింద...",NaN,NaN,NaN,NaN,NaN,NaN
2,అదానీ పోర్ట్స్ అండ్ స్పెషల్ ఎకనామిక్ జోన్ లిమి...,532921,అదానిపోర్ట్స్,INE742F01042,సేవలు,మెరైన్ పోర్ట్ సర్వీసెస్,08-04-2022,839.3,2.68,638.1,...,Adani Ports and Special Economic Zone LimitedT...,['https://upload.wikimedia.org/wikipedia/en/th...,[],NaN,NaN,NaN,NaN,"2019లో, సంస్థ మొట్టమొదటి జాతీయ CSR అవార్డు వేడ...",NaN,NaN
3,అదానీ ట్రాన్స్‌మిషన్ లిమిటెడ్,539254,అదానిత్రన్స్,INE931S01010,శక్తి,విద్యుత్ పంపిణీ,08-04-2022,"2,540.25",3.70,860.1,...,Adani Transmission LimitedType PublicTraded as...,NaN,NaN,అదానీ ఎంటర్ప్రైజెస్ నుండి దశాబ్దాల నాటి ట్రాన్...,NaN,NaN,NaN,NaN,NaN,NaN
4,ఏషియన్ పెయింట్స్ లిమిటెడ్,500820,ASIANPAINT,INE021A01026,మెటీరియల్స్,పెయింట్స్ & వార్నిష్‌లు,08-04-2022,"3,206.25",1.62,"2,488.00",...,Asian Paints Ltd.Type PublicTraded asBSE: 5008...,NaN,NaN,ఈ కంపెనీని నలుగురు స్నేహితులు చంపక్లాల్ చోక్సీ...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,Vivimed Labs Ltd.,532660,వివిమెడ్‌ల్యాబ్,INE526G01021,ఆరోగ్య సంరక్షణ,డ్రగ్స్ & ఫార్మా,04-04-2022,15.5,3.33,14.25,...,Vivimed Labs LimitedType Public Limited Compan...,NaN,NaN,Vivimed నిజానికి 1988లో M/s Emgi ఫార్మాస్యూటిక...,NaN,NaN,NaN,NaN,NaN,NaN
501,VTM లిమిటెడ్.,532893,VTMLTD,INE222F01029,వస్త్రాలు,వస్త్రం,04-04-2022,45.85,4.32,22.1,...,VTM may refer to:Nevatim Airbase (IATA code: V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,వాల్‌చంద్‌నగర్ ఇండస్ట్రీస్ లిమిటెడ్,507410,వాల్చన్నాగ్,INE711A01022,మూలధన వస్తువులు,పారిశ్రామిక యంత్రాలు,04-04-2022,53.75,2.77,39.45,...,Walchandnagar Industries LimitedType Public co...,NaN,NaN,వాల్చంద్నగర్ ఇండస్ట్రీస్ను వాల్చంద్ హీరాచంద్ ద...,NaN,NaN,NaN,NaN,NaN,NaN
503,వీజ్మాన్ లిమిటెడ్.,523011,వెయిజ్‌మనిండ్,INE080A01014,వస్త్రాలు,టెక్స్‌టైల్ ప్రాసెసింగ్,04-04-2022,57.45,-0.61,37.15,...,"Weizman(n) is a surname, common among the Jews...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,జీ లెర్న్ లిమిటెడ్.,533287,ZEELEARN,INE565L01011,సేవలు,చదువు,04-04-2022,13.35,2.30,9.75,...,Zee Learn LimitedCountry IndiaHeadquarters Mum...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN